// Command gendocs regenerates docs/cli/*.md from the live cobra command tree (internal/cli.NewRootCmd). See `make docs` and `make docs-check`. This is the mechanism that keeps the CLI reference from drifting out of sync with the actual commands/flags: it isn't hand-maintained prose, it's generated straight from the same Use/Short/flag definitions the binary itself runs.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"

	"github.com/spf13/cobra/doc"

	"github.com/cloudfluent/terragraph/internal/cli"
)

// autogenFooter matches the "###### Auto generated by spf13/cobra on <date>" line doc.GenMarkdownTree appends to every file. It's stripped below: left in, every regeneration would touch every file's timestamp even when no command actually changed, which would make `make docs-check`'s git-diff staleness check fail every day for no reason.
var autogenFooter = regexp.MustCompile(`(?m)\n*###### Auto generated by spf13/cobra on .*\n*\z`)

func main() {
	const outDir = "docs/cli"
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
	root := cli.NewRootCmd("dev")
	// GenMarkdownTree walks the flag set as-is; it never calls Execute, so cobra's lazily-added --version flag (normally wired in by Execute itself) has to be forced on here, or it would silently be missing from the generated docs.
	root.InitDefaultVersionFlag()
	if err := doc.GenMarkdownTree(root, outDir); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}

	entries, err := os.ReadDir(outDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
	for _, e := range entries {
		path := filepath.Join(outDir, e.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			fmt.Fprintln(os.Stderr, "gendocs:", err)
			os.Exit(1)
		}
		cleaned := autogenFooter.ReplaceAll(data, []byte("\n"))
		if err := os.WriteFile(path, cleaned, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "gendocs:", err)
			os.Exit(1)
		}
	}
}
